service: revenue-by-search-2
provider:
  name: aws
  runtime: python3.7
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: joke
          method: get

plugins:
  - serverless-python-requirements